name: lfu_cache
description: High performance LFU cache implementation
version: 1.0.0
homepage: https://github.com/FaFre/lfu_cache

environment:
  sdk: '>3.0.0 <4.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.16.0
